rbstats: overhaul calculation
use more of the cached json for reduced disk IO
and more consistent results

diff --git a/rbstats b/rbstats
--- a/rbstats
+++ b/rbstats
@@ -9,9 +9,9 @@ exec > ~/tmp/rbstats.txt
 
 echo -n "total-packages: "
 ls | wc -l
-buildtried=$(ls */.osc-build-retval | wc -l)
-grep -v '^[02]$' */.osc-build-retval | cut -d/ -f1 > ~/tmp/failed-builds.txt
-grep -v '^0$' */.build-differed | cut -d/ -f1 > ~/tmp/differed-builds.txt
+buildtried=$(ls */.build-jsonresult | wc -l)
+grep -l '"status" : "FTBFS"' */.build-jsonresult | cut -d/ -f1 > ~/tmp/failed-builds.txt
+grep -l '"status" : "unreproducible"' */.build-jsonresult | cut -d/ -f1 > ~/tmp/differed-builds.txt
 grep -v '^0$' */.build-compare-retval | cut -d/ -f1 > ~/tmp/build-compare-differed-builds.txt
 grep -v '^0$' */.build-differed-nachbau | cut -d/ -f1 > ~/tmp/differed-builds-nachbau.txt
 grep -v '^0$' */.build-compare-retval-nachbau | cut -d/ -f1 > ~/tmp/build-compare-differed-builds-nachbau.txt
@@ -20,13 +20,14 @@ buildsemiverified=$(grep '"verified" : [12]' */.build-jsonresult | wc -l)
 buildverified=$(grep '"verified" : 2' */.build-jsonresult | wc -l)
 buildfailed=$(wc -l < ~/tmp/failed-builds.txt)
 buildfailedarch=$(grep "\"status\" : \"notforus\"" */.build-jsonresult | wc -l)
-buildna=$(grep '^[2]$' */.osc-build-retval | wc -l)
+buildfailedwaitdep=$(grep "\"status\" : \"waitdep\"" */.build-jsonresult | wc -l)
+#buildna=$(grep '^[2]$' */.osc-build-retval | wc -l)
 buildsucceeded=$(grep '^0$' */.osc-build-retval | wc -l)
 echo "build-tried: $buildtried"
-echo "build-failed: $((buildfailed-buildfailedarch))"
-echo "build-n-a: $((buildna+buildfailedarch))"
+echo "build-failed: $((buildfailed))"
+echo "build-n-a: $((buildfailedarch+buildfailedwaitdep))"
 echo "build-succeeded: $buildsucceeded"
-[[ $((buildfailed+buildna+buildsucceeded)) == $buildtried ]] || { echo sanity check failed ; exit 27; }
+[[ $((buildfailed+buildfailedarch+buildfailedwaitdep+buildsucceeded)) == $buildtried ]] || { echo sanity check failed ; exit 27; }
 #osc prjresults --csv --arch=x86_64 --repo=standard openSUSE:Factory > ~/tmp/oscpr
 grep -e ';failed$' -e ';unresolvable$' -e ';disabled$' ~/tmp/oscpr > ~/tmp/oscpr.failed
 echo -n "build-official-failed+na: "
