rbstats: dont use subshells and cd
was a bit ugly with CDPATH

diff --git a/rbstats b/rbstats
--- a/rbstats
+++ b/rbstats
@@ -37,7 +37,7 @@ echo "not-bit-by-bit-identical: $(wc -l < ~/tmp/differed-builds.txt)"
 echo "not-bit-by-bit-identicalcheck: $((buildsucceeded-bitidentical))"
 
 
-for p in $(cat ~/tmp/failed-builds.txt) ; do (cd $p && ! cut -d\; -f1 ~/tmp/oscpr.failed | grep -q "^$p$" && ! egrep -q 'Architecture is (excluded|not included)' RPMS/.build.log && ! grep -q "unresolvable: nothing provides " RPMS/.build.log2 && echo $p ) ; done > ~/tmp/failchecklist 2>/dev/null
+for p in $(cat ~/tmp/failed-builds.txt) ; do test -d $p && ! cut -d\; -f1 ~/tmp/oscpr.failed | grep -q "^$p$" && ! egrep -q 'Architecture is (excluded|not included)' $p/RPMS/.build.log && ! grep -q "unresolvable: nothing provides " $p/RPMS/.build.log2 && echo $p ; done > ~/tmp/failchecklist 2>/dev/null
 
 exec 1>&3
 cat ~/tmp/rbstats.txt
@@ -47,4 +47,4 @@ if [[ $final = 1 ]] ; then
     jsonresultmerge * > ~/tmp/reproducible.json
 fi
 echo "untracked dirs:"
-for p in * ; do (cd $p && test -e .osc-build-retval || echo -n "$p " ) ; done
+for p in * ; do test -d $p && test -e $p/.osc-build-retval || echo -n "$p " ; done
